backend:
  name: git-gateway
  branch: main # если у тебя ветка master, замени на master

media_folder: "images"
public_folder: "images"

collections:
  - name: "catalog"
    label: "Каталог аккаунтов"
    files:
      - file: "steamtradeban_items.json"
        label: "Список товаров"
        name: "items"
        fields:
          - label: "Товары"
            name: "items"
            widget: "list"
            summary: "ID {{fields.id}}: {{fields.name}} ({{fields.price}})"
            fields:
              - { label: "ID товара", name: "id", widget: "number", value_type: "int" }
              - { label: "Название (name)", name: "name", widget: "string" }
              - { label: "Цена (price)", name: "price", widget: "string" }
              - { label: "Описание (desc)", name: "desc", widget: "text" }
              - { label: "Категории (cats)", name: "cats", widget: "list", value_type: "int" }
              - { label: "Картинка", name: "img", widget: "image" }
